on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    name: Build
    runs-on: ubuntu-latest
    env:
      environment: prod

    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Deploy to xquare
        uses: team-xquare/xquare-deployment-action@master
        with:
          environment: prod
          access_key: ${{ secrets.XQUARE_ACCESS_KEY }}
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          buildargs: |
            ENVIRONMENT: prod